config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('*')

  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye</h1>
<p>It was nice having you here!</p>
<p><a href="/say/hello">Hello! </a> </p>
<p>
➤ Say <%= link_to "Hello", say_hello_path %> again.
</p>

app/views/say/hello.html.erb
<h1>Hello from rails!</h1>
<p>
    Now the time is: <%= Time.now%>
</p>
<p> This is the time variable form the controller:<%= @time%> @time </p>

<p> Say <a href="/say/goodbye">Goodbye !</a>using a tag </p>

<p>
   Time to say -using helper method in rails :-)
   <%= link_to "Goodbye", say_goodbye_path %>!
</p>
<%# 
<script type="text/javascript">
 setInterval(function(){
   let currentTime = new Date();
   document.body.innerHTML = currentTime.toLocaleString();
}, 1000);
</script>
%>
<%= content_tag(:span, Time.now, id: 'current-time') %>
<script>
  setInterval(() => {
    document.getElementById('current-time').innerText = new Date().toTimeString();
  }, 1000);
</script>

<p>Addition: <%= 1+1 %></p>
<p><%="cow"+" boy"  %></p>
<p>Time in one hour
 <%= 1.hour.from_now.localtime %> 
 </p>

 <p> To see all the files in rails from the controller with a variable.
 </p>

 <% @files.each do |file| %>
 <%= file %>
<% end %>
 